behaviors:
  DugbyAgentBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size:  5120
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.15
        use_actions: true
        demo_path: Demos/DugbyBasicRecord32.demo
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
      curiosity:
        gamma: 0.99
        strength: 0.05  
        network_settings:
         hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 10
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 20000
environment_parameters:
  difficultylevel:
    curriculum:
        - name: FirstLesson
          completion_criteria: 
            measure: reward
            behavior: DugbyAgentBehavior
            signal_smoothing: true
            min_lesson_length: 200
            threshold: 1.5
          value: 1.0
        - name: SecondLesson
          completion_criteria: 
           measure: reward
           behavior: DugbyAgentBehavior
           signal_smoothing: true
           min_lesson_length: 400
           threshold: 1.6
          value: 2.0
        - name: ThirdLesson
          completion_criteria: 
           measure: reward
           behavior: DugbyAgentBehavior
           signal_smoothing: true
           min_lesson_length: 400
           threshold: 1.6
          value: 3.0
        - name: FourthLesson
          completion_criteria: 
           measure: reward
           behavior: DugbyAgentBehavior
           signal_smoothing: true
           min_lesson_length: 400
           threshold: 1.6
          value: 4.0
        - name: FifthLesson
          completion_criteria: 
           measure: reward
           behavior: DugbyAgentBehavior
           signal_smoothing: true
           min_lesson_length: 400
           threshold: 1.6
          value: 5.0
       